# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"

  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/tools/ecs"
    labels:
      - "dependency"
    open-pull-requests-limit: 1
    package-ecosystem: "composer"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"

  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/tools/phpstan"
    labels:
      - "dependency"
    open-pull-requests-limit: 4
    package-ecosystem: "composer"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase-if-necessary"
